#!/bin/bash

set -eu

build_dir="build_$(cat /etc/compilername)"

mkdir -p "/workspace/$build_dir"
cd "/workspace/$build_dir"

rm -f *_*_*_*

conan \
  install ../conan \
  --build=missing \
  --update \
  --profile=windows

cmake \
  -DCMAKE_MODULE_PATH=$PWD \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_TOOLCHAIN_FILE=/opt/cmake-toolchains/linux-x86_64-to-windows-x86_64.cmake \
  ..

make -j $(nproc)
