kind: pipeline
name: default
platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:

  - name: Clone
    image: alpine/git
    commands:
      - git clone https://github.com/rapatas/transmitron.git .
      - git checkout ${DRONE_COMMIT}

  - name: Build Linux x86_64
    image: rapatas-transmitron-linux-x86-64-release
    pull: if-not-exists
    user: 0
    commands:
      - mkdir build-rapatas-transmitron-linux-x86-64-release
      - cd    build-rapatas-transmitron-linux-x86-64-release
      - conan install --build=missing --profile:build=default --profile:host=default ../conan
      - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake ..
      - make -j 6
      - make package

  - name: Build Windows x86_64
    image: rapatas-transmitron-windows-x86-64-release
    pull: if-not-exists
    user: 0
    commands:
      - mkdir build-rapatas-transmitron-windows-x86-64-release
      - cd    build-rapatas-transmitron-windows-x86-64-release
      - conan install ../conan --build=missing --profile:build=default --profile:host=windows
      - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_PREFIX_PATH=/usr/x86_64-w64-mingw32 ..
      - make -j 6
      - make package

  - name: Release Notes
    image: ubuntu:22.04
    pull: if-not-exists
    commands:
      - echo "$(awk -v section=[${DRONE_TAG}] '$2==section{ f=1; next }; /^## /{ f=0; next }; f==1{ print $0 };' ./CHANGELOG.md)" > release_notes_${DRONE_TAG}.md
      - cat release_notes_${DRONE_TAG}.md
    when:
      event: tag

  - name: Release
    image: plugins/github-release
    settings:
      title: "transmitron ${DRONE_TAG}"
      note: ./release_notes_${DRONE_TAG}.md
      api_key:
        from_secret: drone.io-release
      files:
        - build-*/transmitron_*_*.deb
        - build-*/transmitron_*_*.exe
    checksum:
      - md5
      - sha1
      - sha256
      - sha512
      - adler32
      - crc32
    when:
      event: tag
