kind: pipeline
name: all-in-one
platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:

  - name: Clone
    image: alpine/git
    commands:
      - git clone https://github.com/rapatas/transmitron.git .
      - git checkout ${DRONE_COMMIT}

  - name: Build Ubuntu 20.04
    image: rapatas_transmitron_ubuntu-2004_compiler
    pull: if-not-exists
    user: 0
    commands:
      - mkdir build-release-ubuntu-2004-amd64
      - cd    build-release-ubuntu-2004-amd64
      - conan install ../conan/ --build=missing
      - cmake -DCMAKE_MODULE_PATH=$PWD -DCMAKE_BUILD_TYPE=Release ..
      - make -j $(nproc)
      - make package

  - name: Build Ubuntu 18.04
    image: rapatas_transmitron_ubuntu-1804_compiler
    pull: if-not-exists
    user: 0
    commands:
      - mkdir build-release-ubuntu-1804-amd64
      - cd    build-release-ubuntu-1804-amd64
      - conan install ../conan/ --build=missing
      - cmake -DCMAKE_MODULE_PATH=$PWD -DCMAKE_BUILD_TYPE=Release ..
      - make -j $(nproc)
      - make package

  - name: Build Windows
    image: rapatas_transmitron_windows_compiler
    pull: if-not-exists
    user: 0
    commands:
      - mkdir build-release-windows-amd64
      - cd    build-release-windows-amd64
      - conan install ../conan/ --profile=windows --build=missing
      - cmake -DCMAKE_MODULE_PATH=$PWD -DCMAKE_TOOLCHAIN_FILE=/opt/cmake-toolchains/linux-x86_64-to-windows-x86_64.cmake -DCMAKE_BUILD_TYPE=Release ..
      - make -j $(nproc)
      - make package

  - name: Release Notes
    image: ubuntu:20.04
    pull: if-not-exists
    commands:
      - echo "$(awk -v section=[${DRONE_TAG}] '$2==section{ f=1; next }; /^## /{ f=0; next }; f==1{ print $0 };' ./CHANGELOG.md)" > release_notes_${DRONE_TAG}.md
      - cat release_notes_${DRONE_TAG}.md
    when:
      event: tag

  - name: Release
    image: plugins/github-release
    settings:
      title: "transmitron ${DRONE_TAG}"
      note: ./release_notes_${DRONE_TAG}.md
      api_key:
        from_secret: drone.io-release
      files:
        - build-release-*-*/transmitron_*_*.deb
        - build-release-*-*/transmitron_*_*.exe
    checksum:
      - md5
      - sha1
      - sha256
      - sha512
      - adler32
      - crc32
    when:
      event: tag
