#!/bin/bash

set -eu

build_dir="build_$(cat /etc/compilername)"

mkdir -p "/workspace/$build_dir"
cd "/workspace/$build_dir"

conan \
  install ../conan \
  --build=missing \
  --update

cmake \
  -DCMAKE_MODULE_PATH=$PWD \
  -DCMAKE_BUILD_TYPE=Release \
  ..

make -j $(nproc)
