/* Autogenerated by hxtools bin2c */
#ifndef HISTORY_18X14_HPP
#define HISTORY_18X14_HPP 1

class wxBitmap;

extern "C" void bin2c_init_HISTORY_18X14_HPP(void);
extern wxBitmap *bin2c_history_18x14_png;


#endif /* HISTORY_18X14_HPP */
