/* Autogenerated by hxtools bin2c */
#ifndef HISTORY_18X18_HPP
#define HISTORY_18X18_HPP

class wxBitmap;

extern "C" void bin2c_init_HISTORY_18X18_HPP(void);
extern wxBitmap *bin2c_history_18x18_png;


#endif /* HISTORY_18X18_HPP */
