/* Autogenerated by hxtools bin2c */
#include "qos-0.hpp"
#include <wx/bitmap.h>
#include <wx/image.h>
#include <wx/mstream.h>
wxBitmap *bin2c_qos_0_png;
void bin2c_init_QOS_0_HPP(void)
{
	{
		wxMemoryInputStream sm("\211PNG\15\12\32\12\0\0\0\15IHDR\0\0\0\24\0\0\0\24\1\3\0\0\0\267G\217N\0\0\0\6PLTE\377\377\377\0\0\0U\302\323~\0\0\0\1tRNS\0@\346\330f\0\0\0\1bKGD\0\210\5\35H\0\0\0\11pHYs\0\0\13\23\0\0\13\23\1\0\232\234\30\0\0\0\7tIME\7\345\1\21\11\35\21\305\225N\272\0\0\0$IDAT\10\327c``|\300\300\300l\300\300\300$\200\300\237\4\30\30g\0011\27\2W\2\361_\302\30\0\234=\15\253\232n\270p\0\0\0\0IEND\256B`\202", 177);
		bin2c_qos_0_png = new wxBitmap(wxImage(sm, wxBITMAP_TYPE_ANY), -1);
	}
}
