/* Autogenerated by hxtools bin2c */
#include "qos-2.hpp"
#include <wx/bitmap.h>
#include <wx/image.h>
#include <wx/mstream.h>
wxBitmap *bin2c_qos_2_png;
void bin2c_init_QOS_2_HPP(void)
{
	{
		wxMemoryInputStream sm("\211PNG\15\12\32\12\0\0\0\15IHDR\0\0\0\24\0\0\0\24\1\3\0\0\0\267G\217N\0\0\0\6PLTE\377\377\377\0\0\0U\302\323~\0\0\0\1tRNS\0@\346\330f\0\0\0\1bKGD\0\210\5\35H\0\0\0\11pHYs\0\0\13\23\0\0\13\23\1\0\232\234\30\0\0\0\7tIME\7\345\1\21\11\0353\20\365\17^\0\0\0\36IDAT\10\327c``|\300\300\300\374\1\25\177\376\300\300\370\33\25W\2\361_\302\30\0N!*\315mx\352\350\0\0\0\0IEND\256B`\202", 171);
		bin2c_qos_2_png = new wxBitmap(wxImage(sm, wxBITMAP_TYPE_ANY), -1);
	}
}
