/* Autogenerated by hxtools bin2c */
#ifndef PREVIEW_18X18_HPP
#define PREVIEW_18X18_HPP 1

class wxBitmap;

extern "C" void bin2c_init_PREVIEW_18X18_HPP(void);
extern wxBitmap *bin2c_preview_18x18_png;


#endif /* PREVIEW_18X18_HPP */
