/* Autogenerated by hxtools bin2c */
#ifndef PREVIEW_18X14_HPP
#define PREVIEW_18X14_HPP

class wxBitmap;

extern "C" void bin2c_init_PREVIEW_18X14_HPP(void);
extern wxBitmap *bin2c_preview_18x14_png;


#endif /* PREVIEW_18X14_HPP */
