#!/bin/sh -eu

build_dir="build-$(cat /etc/compilername)"

mkdir -p "/workspace/$build_dir"
cd "/workspace/$build_dir"

conan install \
  --build=missing \
  --profile:build=default \
  --profile:host=windows \
  -of . \
  ../conan

cmake \
  -DCMAKE_BUILD_TYPE=Debug \
  -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake \
  -DCMAKE_PREFIX_PATH=/usr/x86_64-w64-mingw32 \
  ..

make -j $(nproc)
