/* Autogenerated by hxtools bin2c */
#ifndef NOT_PINNED_18X18_HPP
#define NOT_PINNED_18X18_HPP 1

class wxBitmap;

extern "C" void bin2c_init_NOT_PINNED_18X18_HPP(void);
extern wxBitmap *bin2c_not_pinned_18x18_png;


#endif /* NOT_PINNED_18X18_HPP */
