/* Autogenerated by hxtools bin2c */
#ifndef PINNED_18X18_HPP
#define PINNED_18X18_HPP

class wxBitmap;

extern "C" void bin2c_init_PINNED_18X18_HPP(void);
extern wxBitmap *bin2c_pinned_18x18_png;


#endif /* PINNED_18X18_HPP */
