/* Autogenerated by hxtools bin2c */
#ifndef SNIPPETS_18X14_HPP
#define SNIPPETS_18X14_HPP 1

class wxBitmap;

extern "C" void bin2c_init_SNIPPETS_18X14_HPP(void);
extern wxBitmap *bin2c_snippets_18x14_png;


#endif /* SNIPPETS_18X14_HPP */
