/* Autogenerated by hxtools bin2c */
#ifndef SNIPPETS_18X18_HPP
#define SNIPPETS_18X18_HPP

class wxBitmap;

extern "C" void bin2c_init_SNIPPETS_18X18_HPP(void);
extern wxBitmap *bin2c_snippets_18x18_png;


#endif /* SNIPPETS_18X18_HPP */
