/* Autogenerated by hxtools bin2c */
#ifndef SUBSCRIPTION_18X18_HPP
#define SUBSCRIPTION_18X18_HPP

class wxBitmap;

extern "C" void bin2c_init_SUBSCRIPTION_18X18_HPP(void);
extern wxBitmap *bin2c_subscription_18x18_png;


#endif /* SUBSCRIPTION_18X18_HPP */
