/* Autogenerated by hxtools bin2c */
#ifndef SUBSCRIPTION_18X14_HPP
#define SUBSCRIPTION_18X14_HPP 1

class wxBitmap;

extern "C" void bin2c_init_SUBSCRIPTION_18X14_HPP(void);
extern wxBitmap *bin2c_subscription_18x14_png;


#endif /* SUBSCRIPTION_18X14_HPP */
