/* Autogenerated by hxtools bin2c */
#ifndef SEND_18X18_HPP
#define SEND_18X18_HPP

class wxBitmap;

extern "C" void bin2c_init_SEND_18X18_HPP(void);
extern wxBitmap *bin2c_send_18x18_png;


#endif /* SEND_18X18_HPP */
