/* Autogenerated by hxtools bin2c */
#ifndef SEND_18X14_HPP
#define SEND_18X14_HPP 1

class wxBitmap;

extern "C" void bin2c_init_SEND_18X14_HPP(void);
extern wxBitmap *bin2c_send_18x14_png;


#endif /* SEND_18X14_HPP */
