/* Autogenerated by hxtools bin2c */
#ifndef PLUS_18X18_HPP
#define PLUS_18X18_HPP 1

class wxBitmap;

extern "C" void bin2c_init_PLUS_18X18_HPP(void);
extern wxBitmap *bin2c_plus_18x18_png;


#endif /* PLUS_18X18_HPP */
